/* 
======================================================================================================
                              Exploring Insights of Datasets
======================================================================================================
Purpose: This script analyzes sales,customer,product and order data to uncover business insights.
It includes:
        - data exploration by country, category, subcategory, age group and order date.
        - key metrics such as total sales, total orders quantity sold, product count are evaluated.
*/

-- Database Exploration

-- dintinction by countries
select distinct(country)
from gold.dim_customers

-- distinct products variations order by category, subcategory
select distinct category , subcategory ,product_name
from gold.dim_products

-- Date Exploration

-- date range for first & last orders
select min(order_date) as first_order_date,
max (order_date) as last_order_date,
DATEDIFF(year,min(order_date),max(order_date)) as order_diff_in_years,
DATEDIFF(month,min(order_date),max(order_date)) as order_diff_in_months,
DATEDIFF(day,min(order_date),max(order_date)) as order_diff_in_days
from gold.fact_sales

-- age groups
select 
min(birthdate) as oldest_birthdate,
datediff(year,min(birthdate),getdate()) as oldest_age,
max (birthdate) as youngest_birthdate,
datediff(year,max(birthdate),getdate()) as youngest_age
from gold.dim_customers

-- Measures Exploration
-- Total Sales
select sum(sales) as total_sales
from gold.fact_sales

-- total items sold
select sum(quantity) as total_items_sold
from gold.fact_sales

-- average selling price
select avg(sales_price) as avg_selling_price
from gold.fact_sales

-- total orders quantity
select count(distinct(order_number)) as total_orders
from gold.fact_sales

-- total products quantity
select count(distinct(product_name)) as total_products
from gold.dim_products

-- total number of products
select count(product_key) as no_of_products
from gold.dim_products

-- total number of customers
select count(customer_key) as no_of_customers
from gold.dim_customers

-- total customers that has placed an order
select count(distinct(customer_key)) as customers_placed_orders
from gold.fact_sales
where quantity >= 1

-- Magnitude

-- generate a report that shows all key metrics of the business
select 'Total Sales' as measure_name, sum(sales) as measure_value 
from gold.fact_sales

union all

select 'Total Quantity' as measure_name,sum(sales) as measure_value
from gold.fact_sales

union all

select 'Average Price' ,avg(sales)
from gold.fact_sales

union all

select 'Total Nr. Orders' ,count(distinct order_number)
from gold.fact_sales

union all

select 'Total Nr. Products' ,count(product_name)
from gold.dim_products

union all

select 'Total Nr. Orders' ,count(customer_key)
from gold.dim_customers

-- total customers by country
select country,count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc

-- total customers by gender
select gender,count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc

-- total customers by product
select category, count(product_key) as total_products
from gold.dim_products
group by category
order by total_products desc

-- avg cost in each category
select category, avg(product_cost) as avg_costs
from gold.dim_products
group by category
order by avg_costs desc

-- total revenue generated for each category
select p.category, sum(f.sales_price) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.category
order by total_revenue desc

-- total revenue generated by each customers
select c.customer_key, c.first_name, c.last_name, sum(f.sales_price) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by c.customer_key, c.first_name, c.last_name
order by total_revenue desc

-- distribution of sold items across countries
select c.country, sum(f.quantity) as total_sold_items
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by c.country
order by total_sold_items desc

-- Ranking

-- top 5 high performing products generared by revenue
select top(5) p.product_name, sum(f.sales_price) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
order by total_revenue desc

-- top 5 low performing products by sales
select top(5) p.product_name, sum(f.sales_price) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.product_name
order by total_revenue

-- top 5 high performing products generared by revenue
select top(5) p.subcategory, sum(f.sales_price) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.subcategory
order by total_revenue desc
